version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_service
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_service
    depends_on:
      - api
    ports:
      - "8501:8501"

