# ---------- build FastAPI image ----------
FROM python:3.11-slim
WORKDIR /app

# install requirements
RUN pip install --no-cache-dir fastapi uvicorn[standard]

# copy src
COPY fastapi_app/ /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

